apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
        selector:
                        name: app
        ports:
                - name: nginxport
                  port: 80
                  nodePort: 30081
        type: NodePort                  
                          
